// This file is @generated by prost-build.
/// Request message for RetrieveCredentials.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RetrieveCredentialsRequest {
    /// Required. The parent resource name of the AuthProvider.
    /// Format:
    /// `projects/{project}/locations/{location}/authProviders/{auth_provider}`
    #[prost(string, tag = "1")]
    pub auth_provider: ::prost::alloc::string::String,
    /// Required. The identity of the end user.
    #[prost(string, tag = "2")]
    pub user_id: ::prost::alloc::string::String,
    /// Optional. The OAuth scopes required for this access.
    #[prost(string, repeated, tag = "3")]
    pub scopes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Optional. The URI to redirect the user to after consent is completed.
    /// This field is required for authproviders using the 3-legged OAuth flow. For
    /// other authprovider types, this field is unused but not rejected.
    #[prost(string, tag = "4")]
    pub continue_uri: ::prost::alloc::string::String,
    /// Optional. Input only. Set this field only if the previous token was expired
    /// or invalid. This value must be the full, previously returned token string.
    /// Will trigger a refresh of the access token with a stored refresh token, if
    /// possible, or a new consent flow.
    #[prost(string, tag = "7")]
    pub force_refresh_token: ::prost::alloc::string::String,
}
/// Response message for RetrieveCredentials.
/// Contains the access tokens and related artifacts.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RetrieveCredentialsResponse {
    /// The result of the RetrieveCredentials call.
    /// This oneof indicates whether credentials were successfully retrieved, or
    /// what action needs to be taken.
    ///
    /// Note: All polling or retries should follow an exponential backoff
    /// (seconds): `0.5`, `1`, `2`, `4`, `8`, etc...
    #[prost(oneof = "retrieve_credentials_response::Result", tags = "1, 2, 3, 4")]
    pub result: ::core::option::Option<retrieve_credentials_response::Result>,
}
/// Nested message and enum types in `RetrieveCredentialsResponse`.
pub mod retrieve_credentials_response {
    /// Message indicating successful retrieval of credentials.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Success {
        /// The retrieved access token or credential for the end user.
        ///
        /// On MCPTool call, for an invalid token OAuth spec says this should
        /// return 401 or 403, but MCPServers may implement this differently. If you
        /// get any flavor of `PERMISSION_DENIED`, retry your original request to
        /// RetrieveCredentials with
        /// \[force_refresh_token\]\[google.cloud.agentidentitycredentials.v1alpha.RetrieveCredentialsRequest.force_refresh_token\]
        /// set to the expired/invalid token string, which will fetch a new token or
        /// initiate a new consent flow.
        #[prost(string, tag = "1")]
        pub token: ::prost::alloc::string::String,
        /// The HTTP header name where the token should be placed.
        #[prost(string, tag = "2")]
        pub header: ::prost::alloc::string::String,
        /// The expiration time of the token.
        ///
        /// This does not guarantee that the token will be valid until this time,
        /// since the token could be revoked earlier. There could also be clock skew
        /// between the auth provider and the client so it may expire slightly
        /// earlier. If not set, the token might be permanent or it may be that the
        /// service does not (or cannot) know when it will expire.
        #[prost(message, optional, tag = "3")]
        pub expire_time: ::core::option::Option<::prost_types::Timestamp>,
        /// The scopes actually associated with the retrieved token.
        ///
        /// End users may have rejected some requested scopes, or the third-party
        /// authorization servers can return a different set of scopes than what was
        /// asked for. Callers should verify that all required scopes for their
        /// intended use are included in this list.
        #[prost(string, repeated, tag = "4")]
        pub scopes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    }
    /// Indicates that the user must visit the provided URI to consent to
    /// delegate permission to the agent to act on their behalf. The caller can
    /// either poll the provided operation, or await the user ID validation
    /// callback
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct UriConsentRequired {
        /// Output only. The URL where the user should be redirected to grant
        /// consent. This will always be present.
        #[prost(string, tag = "1")]
        pub authorization_uri: ::prost::alloc::string::String,
        /// Output only. A one-time, randomly generated value that validates the
        /// entire consent flow is handled by a single user, avoiding CSRF attacks.
        /// It must be submitted with the FinalizeCredentials request to complete the
        /// OAuth exchange. This will always be present. Implemented per
        /// <https://www.rfc-editor.org/rfc/rfc6819#section-5.3.5>
        #[prost(string, tag = "2")]
        pub consent_nonce: ::prost::alloc::string::String,
    }
    /// Indicates that the credential retrieval is pending. The caller should
    /// retry the RetrieveCredentials request after some time.
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Pending {}
    /// Indicates the user has rejected the permission delegation or cancelled the
    /// request.
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct ConsentRejected {}
    /// The result of the RetrieveCredentials call.
    /// This oneof indicates whether credentials were successfully retrieved, or
    /// what action needs to be taken.
    ///
    /// Note: All polling or retries should follow an exponential backoff
    /// (seconds): `0.5`, `1`, `2`, `4`, `8`, etc...
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        /// Message indicating credentials were successfully retrieved.
        #[prost(message, tag = "1")]
        Success(Success),
        /// Message indicating credential retrieval is pending.
        #[prost(message, tag = "2")]
        Pending(Pending),
        /// Message indicating uri based consent is required.
        #[prost(message, tag = "3")]
        UriConsentRequired(UriConsentRequired),
        /// Message indicating consent was rejected.
        #[prost(message, tag = "4")]
        ConsentRejected(ConsentRejected),
    }
}
/// Request message for FinalizeCredentials.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FinalizeCredentialsRequest {
    /// Required. The resource name of the AuthProvider.
    /// Format:
    /// `projects/{project}/locations/{location}/authProviders/{auth_provider}`
    #[prost(string, tag = "1")]
    pub auth_provider: ::prost::alloc::string::String,
    /// Required. The identity of the end user.
    #[prost(string, tag = "2")]
    pub user_id: ::prost::alloc::string::String,
    /// Required. The encrypted state passed back from the consent flow.
    #[prost(bytes = "vec", tag = "3")]
    pub user_id_validation_state: ::prost::alloc::vec::Vec<u8>,
    /// Required. The same consent_nonce value that was provided during redirect in
    /// the UriConsentRequired metadata.
    #[prost(string, tag = "4")]
    pub consent_nonce: ::prost::alloc::string::String,
}
/// Response message for FinalizeCredentials. Intentionally empty
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FinalizeCredentialsResponse {}
/// Generated client implementations.
pub mod auth_provider_credentials_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Service for managing AuthProvider Credentials.
    #[derive(Debug, Clone)]
    pub struct AuthProviderCredentialsServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl AuthProviderCredentialsServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> AuthProviderCredentialsServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> AuthProviderCredentialsServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            AuthProviderCredentialsServiceClient::new(
                InterceptedService::new(inner, interceptor),
            )
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Retrieves authorization credentials for an authprovider, or indicates what
        /// action needs to be taken to obtain credentials.
        /// If the `token` field in the response is populated, credential retrieval
        /// was successful.
        /// If one of the fields in the `status` oneof is populated, further action is
        /// required to obtain credentials, such as redirecting the user for consent.
        /// View comments on `RetrieveCredentialsResponse` for more information.
        pub async fn retrieve_credentials(
            &mut self,
            request: impl tonic::IntoRequest<super::RetrieveCredentialsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RetrieveCredentialsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/google.cloud.agentidentitycredentials.v1alpha.AuthProviderCredentialsService/RetrieveCredentials",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "google.cloud.agentidentitycredentials.v1alpha.AuthProviderCredentialsService",
                        "RetrieveCredentials",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Finalizes the credentials after a successful consent flow.
        pub async fn finalize_credentials(
            &mut self,
            request: impl tonic::IntoRequest<super::FinalizeCredentialsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::FinalizeCredentialsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/google.cloud.agentidentitycredentials.v1alpha.AuthProviderCredentialsService/FinalizeCredentials",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "google.cloud.agentidentitycredentials.v1alpha.AuthProviderCredentialsService",
                        "FinalizeCredentials",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
