use serde::{Deserialize, Serialize}; /*
                                      * Compute Engine API
                                      *
                                      * Creates and runs virtual machines on Google Cloud Platform.
                                      *
                                      * The version of the OpenAPI document: v1
                                      *
                                      * Generated by: https://openapi-generator.tech
                                      */

/// GuestAttributesValue : Array of guest attribute namespace/key/value tuples.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GuestAttributesValue {
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<crate::google_rest_apis::compute_v1::models::GuestAttributesEntry>>,
}

impl GuestAttributesValue {
    /// Array of guest attribute namespace/key/value tuples.
    pub fn new() -> GuestAttributesValue {
        GuestAttributesValue { items: None }
    }
}
