use serde::{Deserialize, Serialize}; /*
                                      * Compute Engine API
                                      *
                                      * Creates and runs virtual machines on Google Cloud Platform.
                                      *
                                      * The version of the OpenAPI document: v1
                                      *
                                      * Generated by: https://openapi-generator.tech
                                      */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NodeTemplateNodeTypeFlexibility {
    #[serde(rename = "cpus", skip_serializing_if = "Option::is_none")]
    pub cpus: Option<String>,
    #[serde(rename = "localSsd", skip_serializing_if = "Option::is_none")]
    pub local_ssd: Option<String>,
    #[serde(rename = "memory", skip_serializing_if = "Option::is_none")]
    pub memory: Option<String>,
}

impl NodeTemplateNodeTypeFlexibility {
    pub fn new() -> NodeTemplateNodeTypeFlexibility {
        NodeTemplateNodeTypeFlexibility {
            cpus: None,
            local_ssd: None,
            memory: None,
        }
    }
}
