use serde::{Deserialize, Serialize}; /*
                                      * Compute Engine API
                                      *
                                      * Creates and runs virtual machines on Google Cloud Platform.
                                      *
                                      * The version of the OpenAPI document: v1
                                      *
                                      * Generated by: https://openapi-generator.tech
                                      */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NodeGroupsAddNodesRequest {
    /// Count of additional nodes to be added to the node group.
    #[serde(
        rename = "additionalNodeCount",
        skip_serializing_if = "Option::is_none"
    )]
    pub additional_node_count: Option<i32>,
}

impl NodeGroupsAddNodesRequest {
    pub fn new() -> NodeGroupsAddNodesRequest {
        NodeGroupsAddNodesRequest {
            additional_node_count: None,
        }
    }
}
