use serde::{Deserialize, Serialize}; /*
                                      * Compute Engine API
                                      *
                                      * Creates and runs virtual machines on Google Cloud Platform.
                                      *
                                      * The version of the OpenAPI document: v1
                                      *
                                      * Generated by: https://openapi-generator.tech
                                      */

/// RegionInstanceGroupManagerPatchInstanceConfigReq : RegionInstanceGroupManagers.patchPerInstanceConfigs

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RegionInstanceGroupManagerPatchInstanceConfigReq {
    /// The list of per-instance configurations to insert or patch on this managed instance group.
    #[serde(rename = "perInstanceConfigs", skip_serializing_if = "Option::is_none")]
    pub per_instance_configs:
        Option<Vec<crate::google_rest_apis::compute_v1::models::PerInstanceConfig>>,
}

impl RegionInstanceGroupManagerPatchInstanceConfigReq {
    /// RegionInstanceGroupManagers.patchPerInstanceConfigs
    pub fn new() -> RegionInstanceGroupManagerPatchInstanceConfigReq {
        RegionInstanceGroupManagerPatchInstanceConfigReq {
            per_instance_configs: None,
        }
    }
}
