use serde::{Deserialize, Serialize}; /*
                                      * Compute Engine API
                                      *
                                      * Creates and runs virtual machines on Google Cloud Platform.
                                      *
                                      * The version of the OpenAPI document: v1
                                      *
                                      * Generated by: https://openapi-generator.tech
                                      */

/// ResourcePolicyResourceStatus : Contains output only fields. Use this sub-message for all output fields set on ResourcePolicy. The internal structure of this \"status\" field should mimic the structure of ResourcePolicy proto specification.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ResourcePolicyResourceStatus {
    #[serde(rename = "instanceSchedulePolicy", skip_serializing_if = "Option::is_none")]
    pub instance_schedule_policy: Option<Box<crate::google_rest_apis::compute_v1::models::ResourcePolicyResourceStatusInstanceSchedulePolicyStatus>>,
}

impl ResourcePolicyResourceStatus {
    /// Contains output only fields. Use this sub-message for all output fields set on ResourcePolicy. The internal structure of this \"status\" field should mimic the structure of ResourcePolicy proto specification.
    pub fn new() -> ResourcePolicyResourceStatus {
        ResourcePolicyResourceStatus {
            instance_schedule_policy: None,
        }
    }
}
