use serde::{Deserialize, Serialize}; /*
                                      * Compute Engine API
                                      *
                                      * Creates and runs virtual machines on Google Cloud Platform.
                                      *
                                      * The version of the OpenAPI document: v1
                                      *
                                      * Generated by: https://openapi-generator.tech
                                      */

/// Screenshot : An instance's screenshot.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Screenshot {
    /// [Output Only] The Base64-encoded screenshot data.
    #[serde(rename = "contents", skip_serializing_if = "Option::is_none")]
    pub contents: Option<String>,
    /// [Output Only] Type of the resource. Always compute#screenshot for the screenshots.
    #[serde(rename = "kind", skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,
}

impl Screenshot {
    /// An instance's screenshot.
    pub fn new() -> Screenshot {
        Screenshot {
            contents: None,
            kind: None,
        }
    }
}
