use serde::{Deserialize, Serialize}; /*
                                      * Compute Engine API
                                      *
                                      * Creates and runs virtual machines on Google Cloud Platform.
                                      *
                                      * The version of the OpenAPI document: v1
                                      *
                                      * Generated by: https://openapi-generator.tech
                                      */

/// ShieldedInstanceIdentity : A Shielded Instance Identity.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ShieldedInstanceIdentity {
    #[serde(rename = "encryptionKey", skip_serializing_if = "Option::is_none")]
    pub encryption_key:
        Option<Box<crate::google_rest_apis::compute_v1::models::ShieldedInstanceIdentityEntry>>,
    /// [Output Only] Type of the resource. Always compute#shieldedInstanceIdentity for shielded Instance identity entry.
    #[serde(rename = "kind", skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,
    #[serde(rename = "signingKey", skip_serializing_if = "Option::is_none")]
    pub signing_key:
        Option<Box<crate::google_rest_apis::compute_v1::models::ShieldedInstanceIdentityEntry>>,
}

impl ShieldedInstanceIdentity {
    /// A Shielded Instance Identity.
    pub fn new() -> ShieldedInstanceIdentity {
        ShieldedInstanceIdentity {
            encryption_key: None,
            kind: None,
            signing_key: None,
        }
    }
}
