use serde::{Deserialize, Serialize}; /*
                                      * Compute Engine API
                                      *
                                      * Creates and runs virtual machines on Google Cloud Platform.
                                      *
                                      * The version of the OpenAPI document: v1
                                      *
                                      * Generated by: https://openapi-generator.tech
                                      */

/// UrlMapTestHeader : HTTP headers used in UrlMapTests.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UrlMapTestHeader {
    /// Header name.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Header value.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl UrlMapTestHeader {
    /// HTTP headers used in UrlMapTests.
    pub fn new() -> UrlMapTestHeader {
        UrlMapTestHeader {
            name: None,
            value: None,
        }
    }
}
