use serde::{Deserialize, Serialize}; /*
                                      * BigQuery API
                                      *
                                      * A data platform for customers to create, manage, share and query data.
                                      *
                                      * The version of the OpenAPI document: v2
                                      *
                                      * Generated by: https://openapi-generator.tech
                                      */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Job {
    #[serde(rename = "configuration", skip_serializing_if = "Option::is_none")]
    pub configuration: Option<Box<crate::google_rest_apis::bigquery_v2::models::JobConfiguration>>,
    /// [Output-only] A hash of this resource.
    #[serde(rename = "etag", skip_serializing_if = "Option::is_none")]
    pub etag: Option<String>,
    /// [Output-only] Opaque ID field of the job
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "jobReference", skip_serializing_if = "Option::is_none")]
    pub job_reference: Option<Box<crate::google_rest_apis::bigquery_v2::models::JobReference>>,
    /// [Output-only] The type of the resource.
    #[serde(rename = "kind", skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,
    /// [Output-only] A URL that can be used to access this resource again.
    #[serde(rename = "selfLink", skip_serializing_if = "Option::is_none")]
    pub self_link: Option<String>,
    #[serde(rename = "statistics", skip_serializing_if = "Option::is_none")]
    pub statistics: Option<Box<crate::google_rest_apis::bigquery_v2::models::JobStatistics>>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Box<crate::google_rest_apis::bigquery_v2::models::JobStatus>>,
    /// [Output-only] Email address of the user who ran the job.
    #[serde(rename = "user_email", skip_serializing_if = "Option::is_none")]
    pub user_email: Option<String>,
}

impl Job {
    pub fn new() -> Job {
        Job {
            configuration: None,
            etag: None,
            id: None,
            job_reference: None,
            kind: None,
            self_link: None,
            statistics: None,
            status: None,
            user_email: None,
        }
    }
}
