use serde::{Deserialize, Serialize}; /*
                                      * BigQuery API
                                      *
                                      * A data platform for customers to create, manage, share and query data.
                                      *
                                      * The version of the OpenAPI document: v2
                                      *
                                      * Generated by: https://openapi-generator.tech
                                      */

/// TableListTablesInnerView : Additional details for a view.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TableListTablesInnerView {
    /// True if view is defined in legacy SQL dialect, false if in standard SQL.
    #[serde(rename = "useLegacySql", skip_serializing_if = "Option::is_none")]
    pub use_legacy_sql: Option<bool>,
}

impl TableListTablesInnerView {
    /// Additional details for a view.
    pub fn new() -> TableListTablesInnerView {
        TableListTablesInnerView {
            use_legacy_sql: None,
        }
    }
}
