use serde::{Deserialize, Serialize}; /*
                                      * BigQuery API
                                      *
                                      * A data platform for customers to create, manage, share and query data.
                                      *
                                      * The version of the OpenAPI document: v2
                                      *
                                      * Generated by: https://openapi-generator.tech
                                      */

/// TestIamPermissionsResponse : Response message for `TestIamPermissions` method.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TestIamPermissionsResponse {
    /// A subset of `TestPermissionsRequest.permissions` that the caller is allowed.
    #[serde(rename = "permissions", skip_serializing_if = "Option::is_none")]
    pub permissions: Option<Vec<String>>,
}

impl TestIamPermissionsResponse {
    /// Response message for `TestIamPermissions` method.
    pub fn new() -> TestIamPermissionsResponse {
        TestIamPermissionsResponse { permissions: None }
    }
}
