use serde::{Deserialize, Serialize}; /*
                                      * Cloud Storage JSON API
                                      *
                                      * Stores and retrieves potentially large, immutable data objects.
                                      *
                                      * The version of the OpenAPI document: v1
                                      *
                                      * Generated by: https://openapi-generator.tech
                                      */

/// BucketBilling : The bucket's billing configuration.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BucketBilling {
    /// When set to true, Requester Pays is enabled for this bucket.
    #[serde(rename = "requesterPays", skip_serializing_if = "Option::is_none")]
    pub requester_pays: Option<bool>,
}

impl BucketBilling {
    /// The bucket's billing configuration.
    pub fn new() -> BucketBilling {
        BucketBilling {
            requester_pays: None,
        }
    }
}
