use serde::{Deserialize, Serialize}; /*
                                      * Artifact Registry API
                                      *
                                      * Store and manage build artifacts in a scalable and integrated service built on Google infrastructure.
                                      *
                                      * The version of the OpenAPI document: v1
                                      *
                                      * Generated by: https://openapi-generator.tech
                                      */

use crate::google_rest_apis::artifactregistry_v1::models;

/// ListNpmPackagesResponse : The response from listing npm packages.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListNpmPackagesResponse {
    /// The token to retrieve the next page of artifacts, or empty if there are no more artifacts to return.
    #[serde(rename = "nextPageToken", skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
    /// The npm packages returned.
    #[serde(rename = "npmPackages", skip_serializing_if = "Option::is_none")]
    pub npm_packages: Option<Vec<models::NpmPackage>>,
}

impl ListNpmPackagesResponse {
    /// The response from listing npm packages.
    pub fn new() -> ListNpmPackagesResponse {
        ListNpmPackagesResponse {
            next_page_token: None,
            npm_packages: None,
        }
    }
}
