use serde::{Deserialize, Serialize}; /*
                                      * Artifact Registry API
                                      *
                                      * Store and manage build artifacts in a scalable and integrated service built on Google infrastructure.
                                      *
                                      * The version of the OpenAPI document: v1
                                      *
                                      * Generated by: https://openapi-generator.tech
                                      */

use crate::google_rest_apis::artifactregistry_v1::models;

/// UploadYumArtifactResponse : The response of the completed artifact upload operation. This response is contained in the Operation and available to users.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UploadYumArtifactResponse {
    /// The Yum artifacts updated.
    #[serde(rename = "yumArtifacts", skip_serializing_if = "Option::is_none")]
    pub yum_artifacts: Option<Vec<models::YumArtifact>>,
}

impl UploadYumArtifactResponse {
    /// The response of the completed artifact upload operation. This response is contained in the Operation and available to users.
    pub fn new() -> UploadYumArtifactResponse {
        UploadYumArtifactResponse {
            yum_artifacts: None,
        }
    }
}
