use serde::{Deserialize, Serialize}; /*
                                      * Cloud Resource Manager API
                                      *
                                      * Creates, reads, and updates metadata for Google Cloud Platform resource containers.
                                      *
                                      * The version of the OpenAPI document: v3
                                      *
                                      * Generated by: https://openapi-generator.tech
                                      */

use crate::google_rest_apis::cloudresourcemanager_v3::models;

/// ListTagHoldsResponse : The ListTagHolds response.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListTagHoldsResponse {
    /// Pagination token. If the result set is too large to fit in a single response, this token is returned. It encodes the position of the current result cursor. Feeding this value into a new list request with the `page_token` parameter gives the next page of the results. When `next_page_token` is not filled in, there is no next page and the list returned is the last page in the result set. Pagination tokens have a limited lifetime.
    #[serde(rename = "nextPageToken", skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
    /// A possibly paginated list of TagHolds.
    #[serde(rename = "tagHolds", skip_serializing_if = "Option::is_none")]
    pub tag_holds: Option<Vec<models::TagHold>>,
}

impl ListTagHoldsResponse {
    /// The ListTagHolds response.
    pub fn new() -> ListTagHoldsResponse {
        ListTagHoldsResponse {
            next_page_token: None,
            tag_holds: None,
        }
    }
}
