use serde::{Deserialize, Serialize}; /*
                                      * Cloud Resource Manager API
                                      *
                                      * Creates, reads, and updates metadata for Google Cloud Platform resource containers.
                                      *
                                      * The version of the OpenAPI document: v3
                                      *
                                      * Generated by: https://openapi-generator.tech
                                      */

use crate::google_rest_apis::cloudresourcemanager_v3::models;

/// SetIamPolicyRequest : Request message for `SetIamPolicy` method.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetIamPolicyRequest {
    #[serde(rename = "policy", skip_serializing_if = "Option::is_none")]
    pub policy: Option<Box<models::Policy>>,
    /// OPTIONAL: A FieldMask specifying which fields of the policy to modify. Only the fields in the mask will be modified. If no mask is provided, the following default mask is used: `paths: \"bindings, etag\"`
    #[serde(rename = "updateMask", skip_serializing_if = "Option::is_none")]
    pub update_mask: Option<String>,
}

impl SetIamPolicyRequest {
    /// Request message for `SetIamPolicy` method.
    pub fn new() -> SetIamPolicyRequest {
        SetIamPolicyRequest {
            policy: None,
            update_mask: None,
        }
    }
}
