name: tests & formatting
on: 
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
      - run: cargo fmt -- --check && cargo test -p gcloud-sdk --features rest,id-token-verify,axum,reqwest-middleware && cargo test -p gcloud-sdk --no-default-features --features tls-webpki-roots,id-token-verify && cargo test -p gcloud-sdk --no-default-features --features tls-roots,jwt-rust-crypto,id-token-verify,axum,reqwest-middleware #&& cargo clippy -- -Dwarnings && cargo test --all-features
