name: tests & formatting
on: 
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
      - run: cargo fmt -- --check && cargo test -p gcloud-sdk --features rest #&& cargo clippy -- -Dwarnings && cargo test --all-features
